import { assert } from "chai";
import { resolveLiveAgentCredentials } from "./liveAgentCredentials";
import type { WorkflowTestApi } from "../src/modules/contextPanel/workflowTestTypes";

declare const Zotero: any;
declare const Services: any;

describe("live retrieval planner Auto output allowance", function () {
  this.timeout(60000);

  it("returns bilingual search variants using the configured DeepSeek model", async function () {
    const profile = Services.dirsvc.get("ProfD", Ci.nsIFile).path;
    const dataDir = Zotero.DataDirectory.dir;
    const devProfile =
      /\.zotero-dev\/?$/.test(profile) && /\/zotero-dev\/?$/.test(dataDir);
    const isolatedTestProfile =
      /\/\.scaffold\/test\/profile\/?$/.test(profile) &&
      /\/\.scaffold\/test\/data\/?$/.test(dataDir);
    assert.isTrue(
      devProfile || isolatedTestProfile,
      "Use a disposable profile",
    );
    const credentials = await resolveLiveAgentCredentials({
      requestedModel: "deepseek-flash",
    });
    assert.isOk(credentials, "Configure DeepSeek in the disposable profile");
    const addon = Zotero.LLMForZotero;
    const api = addon.api.workflowTest as WorkflowTestApi;
    const toolkit = addon.data.ztoolkit;
    const originalGetGlobal = toolkit.getGlobal;
    const nativeFetch = originalGetGlobal.call(toolkit, "fetch");
    const requests: Array<{
      model: string;
      maxTokens: number | null;
      thinking: unknown;
      status?: number;
      stopReason?: string;
      usage?: unknown;
    }> = [];
    toolkit.getGlobal = function (name: string) {
      if (name !== "fetch") return originalGetGlobal.call(toolkit, name);
      return async (url: string, init?: RequestInit) => {
        const body = JSON.parse(String(init?.body || "{}"));
        const record = {
          model: String(body.model || ""),
          maxTokens: body.max_tokens ?? body.max_output_tokens ?? null,
          thinking: body.thinking,
        } as (typeof requests)[number];
        if (body.messages || body.input) requests.push(record);
        const response = await nativeFetch(url, init);
        record.status = response.status;
        if (response.ok && !body.stream) {
          const json = await response.clone().json();
          record.stopReason =
            json.stop_reason ?? json.choices?.[0]?.finish_reason;
          record.usage = json.usage;
        }
        return response;
      };
    };
    const startedAt = Date.now();
    try {
      const query =
        "哪些论文研究了神经表征随时间的变化，以及解码如何保持稳定？";
      const plan = await api.planRetrievalQuery({
        ...credentials!,
        authMode: "api_key",
        providerProtocol: credentials!.providerProtocol as
          | "anthropic_messages"
          | "openai_chat_compat",
        query,
        hasRetrievalContext: true,
        sourceSamples: [
          "Representational drift in visual cortex. Neural population activity changes across days while behavior remains stable.",
          "Stable decoding from a drifting neural population code. Readout adaptation preserves task performance.",
        ],
      });
      const evidence = {
        profile,
        dataDir,
        elapsedMs: Date.now() - startedAt,
        requests,
        plan,
      };
      // Synthetic document samples only; no credentials or headers are saved.
      await Zotero.File.putContentsAsync(
        PathUtils.join(dataDir, "issue-462-auto-planner-live.json"),
        JSON.stringify(evidence, null, 2),
      );
      assert.isNotEmpty(requests, "Capture the real provider request");
      assert.isTrue(
        requests.every(
          (request) => request.maxTokens === null || request.maxTokens > 4096,
        ),
        JSON.stringify(requests),
      );
      assert.isAtLeast(plan.variants.length, 1, JSON.stringify(evidence));
      assert.isAtMost(plan.variants.length, 6);
      assert.equal(plan.effectiveQueries[0], query);
      assert.isTrue(plan.variants.some((variant) => /[a-z]{3}/i.test(variant)));
      assert.isTrue(
        plan.variants.some((variant) => /[\u4e00-\u9fff]/.test(variant)),
      );
      assert.include(
        plan.notes.join(" "),
        "generated by the retrieval planner",
      );
      assert.notInclude(
        requests.map((request) => request.stopReason),
        "max_tokens",
      );
    } finally {
      toolkit.getGlobal = originalGetGlobal;
    }
  });
});
